name: crudflutter
description: A simple Flutter CRUD app with SQLite

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.9.0

flutter:
  uses-material-design: true
